### ISSUE TITLE
Tankbar info wrong, no pressure info for 2nd, 3rd,... gas, heatmap uses wrong gas

### ISSUE THREAD

**Issue by sfuchs79** [subsurface/subsurface#562] opened 2017-09-09 19:48 UTC
Found a few issues which were introduced between ~4.6.4.390 and now (~4.6.4.790):
- The tankbar info in the graph is incorrect for all of my logged or planned dives. Tankbar always shows 1st gas.
- In the infobox of the graph a pressure value is displayed only for the 1st gas while at the same moment there is a correct pressure graph also for the 2nd, 3rd,... gas.
- Sometimes there are some incorrect vertical lines connecting the pressure graph of two gases.

![grafik](https://user-images.githubusercontent.com/25316050/30243277-627d56a4-95a6-11e7-86cb-5a7a2e28571c.png)

![grafik](https://user-images.githubusercontent.com/25316050/30243395-78bf5140-95a8-11e7-93fd-f123eb3b8afc.png)

**Comment by sfuchs79** [comment] 2017-09-11 17:08
Also the tissue heatmap is not correct any more. Also here no other gas then 1st gas is considered.

**Comment by dirkhh** [comment] 2017-09-13 17:33
My guess is that these are all side effects from some of Linus' changes to the tank handling.
Thanks for reporting them. Now someone needs to track them down and fix them :-/

**Comment by dirkhh** [comment] 2017-09-14 03:38
The tank bar and info box are now fixed.
Linus asked for a sample dive that shows the artifact in the picture
and @atdotde might want to look at the heat map :-)

**Comment by dirkhh** [comment] 2017-09-23 18:49
Ha, @neolit123 - no, this one is now assigned to @atdotde 
The heatmap is his baby :-)

**Comment by atdotde** [comment] 2017-10-17 11:28
@sfuchs79 can you give me a concrete example of a dive where the heat map does not follow gas changes with current master? I cannot reproduce this bug anymore.

**Comment by sfuchs79** [comment] 2017-10-17 11:36
Current master:
![grafik](https://user-images.githubusercontent.com/25316050/31662666-a15d043a-b33f-11e7-8b6b-2748d6d77738.png)

4.6.4:
![grafik](https://user-images.githubusercontent.com/25316050/31662696-c7102a0e-b33f-11e7-87ca-c0195b7ed035.png)

Looks definitively different - Maybe the question is: What is correct and what is wrong? Maybe even 4.6.4 was wrong?!

**Comment by sfuchs79** [comment] 2017-10-17 11:52
Hmmm.. honestly I have to admit that current master heatmap looks "nicer" compared to 4.6.4. But have we been aware of the fact that it was broken in 4.6.4 and you then fixed it?
If this is the case then: Sorry, I was too focused on the difference and was immediately deciding: 4.6.4 good (what else?) - current master broken after the changes Linus did...
@atdotde But I'm waiting for your final conclusion now...

**Comment by glance-** [comment] 2017-10-17 12:37
To me it looks like master renders the head map with the back gas all the way, and that's not right.

**Closed as completed** 2017-10-18 10:34 UTC
Labels: bug, dive-profile, dive-equipment, priority-low, release-blocker
