### ISSUE TITLE
Subsurface mobile: Showing heart rate and skin temperature of Scubapro G2

### ISSUE THREAD

**Issue by satoschu** [subsurface/subsurface#2832] opened 2020-05-13 18:01 UTC
### Describe the issue:

- [ ] Bug
- [ ] Change request
- [x] New feature request
- [ ] Discussion request

### Issue long description:

Is it possible to show additionally heart rate and skin temperature in the graph of subsurface mobile from the Scubapro G2 device dive data.

**Comment by neufeind** [comment] 2023-08-16 06:49
Dupe/related with #1186

**Comment by mikeller** [comment] 2023-08-17 01:06
Closing as duplicate of #1186.

**Closed as completed by mikeller** 2023-08-17 01:06 UTC
