### ISSUE TITLE
Map not working under Windows 10 with 4.8.0-100

### ISSUE THREAD

**Issue by sfuchs79** [subsurface/subsurface#1500] opened 2018-07-12 20:55 UTC
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

With latest continuous build 4.8.0-100 and with my own MXE based Windows build based on master the map is not working.
I only see the (well known) error message in the map window.
I guess this comes from one of the latest commits because my last build with working map can't be longer than 2-3 days ago.

### Operating system:

Windows 10

### Subsurface version:

4.8.0-100

### Mentions:

@dirkhh @janiversen @jbygdell @bstoeger

**Comment by janiversen** [comment] 2018-07-12 20:56
Can you please mail me the log, that might reveal what the problem is. Thanks in advance.

**Comment by janiversen** [comment] 2018-07-12 20:58
your own windows build, might not have catched up with the CMake change. There is a new file
subsurface/subsurface-helper.cpp that replaces subsurface-*-helper.cpp

**Comment by sfuchs79** [comment] 2018-07-12 20:59
Error message from 4.8.0-100 from Travis:
qrc:/qml/MapWidget.qml:5:1: module "org.subsurfacedivelog.mobile" is not installed
QUrl("qrc:/qml/MapWidget.qml") failed to load with status: QQuickWidget::Status(Error)

**Comment by janiversen** [comment] 2018-07-12 21:02
That looks exactly as if your build does not use the new setup (files in subsurface)

The registrations was moved to subsurface/subsurface-helper.cpp

Let me just do another test, now my patch is merged (I tested on my local branch).

**Comment by janiversen** [comment] 2018-07-12 21:05
just rebuild master (to be sure), it works fine on a Mac.

**Comment by sfuchs79** [comment] 2018-07-12 21:07
Have you tested the Windows build from Travis?
The error from above is not from "my" build but from using the Travis CI Windows installer. This is what I installed to exclude anything coming from my build environment.

**Comment by janiversen** [comment] 2018-07-12 21:10
No I do not have access to windows, I am a Mac and iOS type of developer.

But based on your information, it looks like travis did not pickup the merge correctly, there are no changes in the actual code, just moved all qmlRegisterCode to register_qml_type().

@dirkhh if this is not something easy, then lets wait with this merge until after the release. It really looks like the "only source move" merge.

**Comment by janiversen** [comment] 2018-07-12 21:10
watt = revert

**Comment by sfuchs79** [comment] 2018-07-12 21:16
Would be great if s.o. else could also test the Windows CI installer.

Unfortunately I won't be able to bisect or simple revert some of the latest commits and test again. Started a rebuild of my MXE plus will got to bed now :-)

**Comment by janiversen** [comment] 2018-07-12 21:49
@dirkhh did a little analysis if the windows did not get the changes subsurface directoty but in subsurface/* directories this oroblem would happen

**Comment by neolit123** [comment] 2018-07-12 21:57
@sfuchs79 i was testing the `-100` Win32 build from our CI one hour ago and the map did no throw errors for me.

could it be a case that your MXE build and the `-100` build somehow mixed?

> qrc:/qml/MapWidget.qml:5:1: module "org.subsurfacedivelog.mobile" is not installed
QUrl("qrc:/qml/MapWidget.qml") failed to load with status: QQuickWidget::Status(Error)

the above message is very weird because i think for that to happen the file `mapwidget.cpp` would have to be missing from the build.

**Comment by neolit123** [comment] 2018-07-12 22:07
> could it be a case that your MXE build and the -100 build somehow mixed?

oh, wait a minute. i installed `-100` over my previous install.
the map is indeed broken in the `-100` installer.

**Comment by janiversen** [comment] 2018-07-12 22:29
actually it is more likely that qmlRegisterType which used to be in mapwidget is not called. that call moved to subsurface_helper.cpp

**Comment by neolit123** [comment] 2018-07-12 22:42
submitted fix.

**Closed as completed** 2018-07-13 12:18 UTC
Labels: bug, widget-map
