### ISSUE TITLE
Unable to add new Location

### ISSUE THREAD

**Issue by Wardy-uk** [subsurface/subsurface#1804] opened 2018-10-16 13:21 UTC
### Describe the issue:

- [x ] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

Type name of new dive location in Location field
Double click on blue bar
Nothing else happens - unable to set the location on the map, or enter in any other details (lat/long etc)

Also unable to edit existing locations - the Globe at the end of the Location field remains greyed out at all times.

### Operating system:

Running on Win 7

### Subsurface version:

ver 4.8.3 (also occurred on previous versions for circa 6 months)

**Comment by neolit123** [comment] 2018-10-19 13:02
please try the subsurface-4.8.3-213-gcc225a44f234.exe installer from here:
https://github.com/Subsurface-divelog/subsurface/releases

**Comment by bstoeger** [comment] 2018-10-30 14:35
I can reproduce this - will debug later today.

**Comment by bstoeger** [comment] 2018-10-30 18:18
False alarm. I thought it was #1836, but that has been introduced too recently for being responsible for this bug.

**Comment by bstoeger** [comment] 2020-05-03 13:36
I'm closing this as the dive site handling has been completely rewritten since this was reported.

**Closed as completed by bstoeger** 2020-05-03 13:36 UTC
Labels: bug, dive-site
