### ISSUE TITLE
Git storage progress bar text does not fit widget

### ISSUE THREAD

**Issue by atdotde** [subsurface/subsurface#1041] opened 2018-01-12 16:16 UTC
### Describe the issue:

- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

A QProgressBar widget is supposed to grow automatically to fit the text label it contains.
Except it doesn't. This becomes more obvious when running Subsurface in German where
the translated strings are longer but it is present in the English version as well. I tried fix this by turning setLabelText into setLabel but that did not help.

**Comment by neolit123** [comment] 2018-01-12 17:55
@atdotde 

we have a list of `QProgressBar` usages in the tree, but those are fixed in a layout and don't seem to cause troubles:

```
..desktop-widgets> grep QProgress * -rnI
configuredivecomputerdialog.cpp:15:#include <QProgressDialog>
configuredivecomputerdialog.cpp:348:    QProgressDialog *dialog = new QProgressD
ialog("Updating firmware", "", 0, 100);
configuredivecomputerdialog.ui:3948:    <widget class="QProgressBar" name="progr
essBar">
diveshareexportdialog.ui:186:       <widget class="QProgressBar" name="progressB
ar">
downloadfromdivecomputer.ui:186:        <widget class="QProgressBar" name="progr
essBar">
mainwindow.cpp:69:QProgressDialog *progressDialog = NULL;
mainwindow.cpp:2028:    progressDialog = new QProgressDialog(tr("Contacting clou
d service..."), tr("Cancel"), 0, 100, this);
mainwindow.h:15:#include <QProgressDialog>
printdialog.cpp:7:#include <QProgressBar>
printdialog.cpp:94:     progressBar = new QProgressBar();
printdialog.h:12:class QProgressBar;
printdialog.h:26:       QProgressBar *progressBar;
webservices.ui:59:    <widget class="QProgressBar" name="progressBar">
```

instead of `QProgressBar` do you mean the `QProgressDialog` in `mainwindow.cpp`?

edit: oops, i guess the title partially confirms that `Git storage progress bar text does not fit widget`.

**Comment by neolit123** [comment] 2018-01-12 18:08
@atdotde on what OS you are reproducing the issue? on Windows 7 i get a correct resize:

![qprogressdialog](https://user-images.githubusercontent.com/331852/34888790-41a0af7c-f7d4-11e7-9f69-12b2d332772a.jpg)

**Comment by janmulder** [comment] 2018-01-12 18:23
Things also seem to work (even in German :-)) on my Linux box. That said, as my network is fast, I have definitely no time to read the messages, but can see that they are not truncated, and resize between the different messages.

**Comment by atdotde** [comment] 2018-01-12 21:13
I noticed this today on my office iMac with the big screen where at some point I had increased the font size in the preferences. Now, on my laptop, everything did fit in the box but there the font is much smaller. Thus I artificially increased the font size in the preferences, and here you go: 
<img width="1280" alt="screenshot 2018-01-12 22 10 27" src="https://user-images.githubusercontent.com/863957/34895362-b537cc34-f7e5-11e7-9543-4d7840309ba9.png">

**Comment by janmulder** [comment] 2018-01-12 21:36
Well, not sure this "artificially increased" trick shows the issue. That whole screen looks like shit, not only the dialog we are talking about here.

**Comment by atdotde** [comment] 2018-01-12 22:06
No, that was just coming from an ugly font that I had selected:

<img width="1280" alt="screenshot 2018-01-12 23 04 39" src="https://user-images.githubusercontent.com/863957/34897188-1d3e0bac-f7ed-11e7-844a-11347658edae.png">

**Comment by janmulder** [comment] 2018-01-13 08:15
Yes, that convinces me more ... but as we not seem to be able to reproduce on Windows or Linux I am very tempted to call it a bug outside of our code base. Could be Qt or even Os/windowmanager related. 

As it seem to be centered correctly, it could be something related to font metrics. Hmm, that said, we do mess around with font metrics ... and just found the intriguing function:

```
QFont defaultModelFont()
{
	QFont font;
//	font.setPointSizeF(font.pointSizeF() * 0.8);
	return font;
}
```

But do they resize at all? Or are they too small for every string?

**Comment by neolit123** [comment] 2018-01-13 15:16
@atdotde 

what Qt version?
are you building Subsurface yourself on that mac?

here is a patch to try:
```
diff --git a/desktop-widgets/mainwindow.cpp b/desktop-widgets/mainwindow.cpp
index 5cf3dc27f..b0220402d 100644
--- a/desktop-widgets/mainwindow.cpp
+++ b/desktop-widgets/mainwindow.cpp
@@ -13,6 +13,7 @@
 #include <QShortcut>
 #include <QToolBar>
 #include <QStatusBar>
+#include <QFontMetrics>
 
 #include "core/version.h"
 #include "desktop-widgets/divelistview.h"
@@ -77,6 +78,8 @@ extern "C" int updateProgress(const char *text)
 		qDebug() << "git storage:" << text;
 	if (progressDialog) {
 		progressDialog->setLabelText(text);
+		const int width = QFontMetrics(progressDialog->font()).width(progressDialog->labelText()) + 100;
+		progressDialog->resize(width, progressDialog->height());
 		progressDialog->setValue(++progressCounter);
 		if (progressCounter == 100)
 			progressCounter = 0; // yes this is silly, but we really don't know how long it will take

```

works for me on Windows. it does no harm if the auto-resize works, but it could take care of the non-resizing issue.

**Comment by atdotde** [comment] 2018-01-13 15:19
It seems to actually be a Qt problem, I can reproduce this in a a small example program: 
<img width="569" alt="screenshot 2018-01-13 16 14 05" src="https://user-images.githubusercontent.com/863957/34907319-f7f3a4ca-f87c-11e7-99f6-d08e49d0fe5f.png">

Could you please try this on Linux to see if this is a Mac only problem?  
[progresdialogoverlap.zip](https://github.com/Subsurface-divelog/subsurface/files/1628458/progresdialogoverlap.zip)

**Comment by neolit123** [comment] 2018-01-13 15:23
@atdotde @janmulder said that he cannot reproduce it on Windows and Linux. is this on Qt 5.9+ ?

also, we need to test the above patch.

**Comment by atdotde** [comment] 2018-01-13 15:50
@neolit123 we overlapped. I came up with the same workaround as #1045 which solves the problem for me. The problem exists both for off the shelf 5.8 and 5.10.0. In my question about other OSs I was referring to my example program.

**Closed as completed** 2018-01-13 18:13 UTC
Labels: bug, ui-desktop, needs-developer-feedback, qt, bug-hard-to-reproduce, help-wanted
