### ISSUE TITLE
Mac 4.9.7 binary version requires Mac OS 10.15

### ISSUE THREAD

**Issue by stetner** [subsurface/subsurface#3047] opened 2020-10-27 01:00 UTC
### Describe the issue:

- [ ] Bug
- [x] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:

4.9.7 version of the Subsurface.app requires 10.15, not 10,10 (or 10.7) as seen in the doco.
### Operating system:

10.14.6

Mares Puck Pro

### Subsurface version:

4.9.7

unsure

official release

### Steps to reproduce:

Download and the app icon appears with the circle and diagonal meaning it will not run. Dialog says:
You can’t use this version of the application “Subsurface.app” with this version of macOS.
You have macOS 10.14.6. The application requires macOS 10.15 or later.
Probably just needs to be compiled with older SDK.

### Current behavior:

Does not run
### Expected behavior:

Runs
### Mentions:

<img width="1184" alt="Screen Shot 2020-10-27 at 10 59 52" src="https://user-images.githubusercontent.com/9170040/97244137-906efb80-1843-11eb-88e4-6b263011f9e1.png">

**Comment by dirkhh** [comment] 2020-10-27 02:03
Duplicate of #3005 
Same solution as there: https://subsurface-divelog.org/downloads/Subsurface-4.9.7-macOS-10.13+10.14.dmg

**Closed as completed by dirkhh** 2020-10-27 02:03 UTC
